//新的，要顯示在網頁前面的：要擺在最後面
var data_sch = {webs: [
{text: "彰化縣快官國小",img:"kges.png",href: "https://www.kges.chc.edu.tw/"},
{text: "香港蒙特梭利國際學校",img:"ims.png",href: "https://www.ims.edu.hk/"},
{text: "臺北市華興中學",img:"hhhs.png",href: "http://www.hhhs.tp.edu.tw/nss/p/index"},
{text: "馬來西亞麻坡中化中學",img:"chhs.png",href: "http://www.chhs.edu.my/web/"},
{text: "香港宣道國際學校",img:"cais.png",href: "https://www.caisbv.edu.hk/"},
{text: "台北市西松高中",img:"hssh.png",href: "http://www.hssh.tp.edu.tw/"},
{text: "私立正心高中",img:"shsh.png",href: "https://www.shsh.ylc.edu.tw/"},
{text: "私立維多利亞實驗中學",img:"vict.png",href: "https://sites.google.com/a/victoria.ylc.edu.tw/senior/"},
{text: "私立聖功女中",img:"skgsh.png",href: "http://www.skgsh.tn.edu.tw/"},
{text: "私立瀛海高中",img:"yhsh.png",href: "http://net.yhsh.tn.edu.tw/~main/hcy/index1.htm"},
{text: "私立東山高中",img:"tshs.png",href: "http://www.tshs.tp.edu.tw/home.asp"},
{text: "臺北市實踐國中",img:"sjjh.png",href: "http://ww1.sjjh.tp.edu.tw/"},
{text: "私立時雨中學",img:"syjh.png",href: "http://www.syjh.ntpc.edu.tw/nss/p/index"},
{text: "臺北市龍門國中",img:"lmjh.png",href: "http://www.lmjh.tp.edu.tw/"},
{text: "新北市安坑國小",img:"take.png",href: "https://www.takes.ntpc.edu.tw/"},
{text: "臺北市吉林國小",img:"clps.png",href: "http://www.clps.tp.edu.tw/vschool/index2.asp"},
{text: "臺北市東門國小",img:"tmps.png",href: "https://www.tmps.tp.edu.tw/"},
{text: "臺北市興華國小",img:"hhps.png",href: "http://www.hhps.tp.edu.tw/"},
{text: "臺北市金華國小",img:"cups.png",href: "http://www.cups.tp.edu.tw/"},
{text: "臺北市萬福國小",img:"wfps.png",href: "http://www.wfps.tp.edu.tw/"},
{text: "臺北市西園國小",img:"hups.png",href: "http://www.hups.tp.edu.tw/"},
{text: "私立靜心小學",img:"chjh.png",href: "http://www.chjhs.tp.edu.tw/dispPageBox/ELEHP.aspx?ddsPageID=ELEHP"},
{text: "私立再興小學",img:"tsps.png",href: "http://www.tsps.tp.edu.tw/nss/p/index"},
{text: "屏東縣大同國小",img:"dtps.png",href: "http://www.dtps.ptc.edu.tw/"},
{text: "台北市民族實驗國中",img:"mtjh.png",href: "http://www.mtjh.tp.edu.tw/"},
{text: "花蓮縣富源國中",img:"fyjh.png",href: "http://www.fyjh.hlc.edu.tw/"},
{text: "花蓮縣萬榮國中",img:"wljh.png",href: "http://www.wljh.hlc.edu.tw/"},
{text: "花蓮縣鶴岡國小",img:"hgps.png",href: "http://www.hgps.hlc.edu.tw/"},
{text: "花蓮縣萬寧國小",img:"wlip.png",href: "http://www.wlips.hlc.edu.tw/"},
{text: "花蓮縣長良國小",img:"chli.png",href: "http://www.clps.hlc.edu.tw/"},
{text: "花蓮縣東里國小",img:"tlps.png",href: "http://www.tlps.hlc.edu.tw/"},
{text: "新北市插角國小",img:"cgps.png",href: "https://www.cgps.ntpc.edu.tw/"},
{text: "新北市成福國小",img:"chen.png",href: "https://www.chenfu.ntpc.edu.tw/"},
{text: "新北市頭前國中",img:"tqjh.png",href: "https://www.tqjh.ntpc.edu.tw/"},
{text: "新北市福營國中",img:"fuyi.png",href: "https://www.fyjh.ntpc.edu.tw/nss/p/index"},
{text: "新北市中平國中",img:"cpjh.png",href: "https://www.cpjh.ntpc.edu.tw/"},
{text: "新北市瑞芳國中",img:"rfjh.png",href: "https://www.rfjh.ntpc.edu.tw/nss/p/index"},
{text: "新北市柑園國小",img:"gyes.png",href: "https://www.gyes.ntpc.edu.tw/"},
{text: "新北市泰山國中",img:"ttcj.png",href: "https://www.ttcjh.ntpc.edu.tw/nss/p/index"},
{text: "新北市三民高中",img:"smsh.png",href: "http://www.smsh.ntpc.edu.tw/"},
{text: "新北市三芝國中",img:"szjh.png",href: "https://www.szjh.ntpc.edu.tw/"},
{text: "新北市欽賢國中",img:"cejh.png",href: "https://www2.cejh.ntpc.edu.tw/"},
{text: "新北市石碇高中",img:"sdhs.png",href: "https://www.sdhs.ntpc.edu.tw/"},
{text: "新北市汐止國中",img:"hcjs.png",href: "https://www.hcjhs.ntpc.edu.tw/"},
{text: "新北市尖山國中",img:"jsjh.png",href: "https://www.jsjhs.ntpc.edu.tw/"},
{text: "新北市北大高中",img:"dbsh.png",href: "https://www.bdsh.ntpc.edu.tw/"},
{text: "新北市大觀國中",img:"tkjs.png",href: "https://www.tkjhs.ntpc.edu.tw/"},
{text: "新北市中角國小",img:"jjps.png",href: "https://www.jjps.ntpc.edu.tw/"},
{text: "新北市昌福國小",img:"cfps.png",href: "https://www.cfps.ntpc.edu.tw/"},
{text: "新北市建國國小",img:"ckps.png",href: "https://web.ckps.ntpc.edu.tw/"},
{text: "新北市鶯歌國小",img:"ykps.png",href: "https://www.ykes.ntpc.edu.tw/"},
{text: "新北市瑞芳國小",img:"rfes.png",href: "https://www.rfes.ntpc.edu.tw/"},
{text: "新北市天生國小",img:"tisn.png",href: "https://www.tisnes.ntpc.edu.tw/"},
{text: "新北市中正國中",img:"ccjh.png",href: "https://www2.ccjhs.ntpc.edu.tw/"},
{text: "新北市文山國中",img:"wsjh.png",href: "http://www.wsjh.ntpc.edu.tw/default_page.asp"},
{text: "新北市忠孝國中",img:"chjs.png",href: "https://www.chjs.ntpc.edu.tw/"},
{text: "新北市三多國中",img:"sdjh.png",href: "https://www.sdjh.ntpc.edu.tw/"},
{text: "新北市江翠國中",img:"chia.png",href: "https://www.ctjh.ntpc.edu.tw/"},
{text: "宜蘭縣私立中道中學",img:"cdsh.png",href: "http://www.cdsh.ilc.edu.tw/"},
{text: "台中市光華高工",img:"khvs.png",href: "http://w3.khvs.tc.edu.tw/home"},
{text: "新北市新埔國小",img:"spes.png",href: "https://www.spes.ntpc.edu.tw/"},
{text: "新北市秀朗國小",img:"hles.png",href: "http://www.hles.ntpc.edu.tw/default_page.asp"},
{text: "新北市德音國小",img:"tyes.png",href: "https://www.tyes.ntpc.edu.tw/"},
{text: "新北市中山國中",img:"csjh.png",href: "https://web.csjh.ntpc.edu.tw/"},
{text: "新北市五峰國中",img:"wfjh.png",href: "https://www.wfjh.ntpc.edu.tw/"},
{text: "新北市文德國小",img:"wdps.png",href: "https://www.wdps.ntpc.edu.tw/"},
{text: "新北市丹鳳高中",img:"dfsh.png",href: "http://www.dfsh.ntpc.edu.tw/default_page.asp"},
{text: "新北市三和國中",img:"shjh.png",href: "https://www.shjh.ntpc.edu.tw/"},
{text: "新北市三重高中",img:"schs.png",href: "http://www.schs.ntpc.edu.tw/default_page.asp"},
{text: "新北市鷺江國中",img:"ljjh.png",href: "https://www.ljjh.ntpc.edu.tw/"},
{text: "新北市二重國中",img:"ecjh.png",href: "https://www.ecjh.ntpc.edu.tw/"},
{text: "新北市淡水國中",img:"tsjh.png",href: "https://www.tsjh.ntpc.edu.tw/"},
{text: "新北市樟樹國際實中",img:"ctjh.png",href: "https://www.ctjhs.ntpc.edu.tw/"},
{text: "新北市永和國中",img:"jhjh.png",href: "https://www.jhjhs.ntpc.edu.tw/"},
{text: "新北市鶯歌國中",img:"ykjh.png",href: "https://www.ykjhs.ntpc.edu.tw/index.php"},
{text: "新北市樹林高中",img:"shul.png",href: "http://www.slsh.ntpc.edu.tw/default_page.asp"},
{text: "新北市土城國中",img:"tcjh.png",href: "https://www.tcjh.ntpc.edu.tw/"},
{text: "新北市海山高中",img:"hshs.png",href: "http://www.hshs.ntpc.edu.tw/nss/p/index"},
{text: "新北市溪洲國小",img:"sips.png",href: "https://www.sips.ntpc.edu.tw/"},
{text: "新北市文聖國小",img:"wses.png",href: "https://www.wses.ntpc.edu.tw/"},
{text: "新北市江翠國小",img:"ctes.png",href: "https://www.ctes.ntpc.edu.tw/"},
{text: "新北市達觀國小",img:"dgej.png",href: "https://www.dgejh.ntpc.edu.tw/"},
{text: "新北市淡水國小",img:"tans.png",href: "https://www.tsps.ntpc.edu.tw/"},
{text: "新北市桃子腳國中小",img:"tykj.png",href: "https://www.tykjh.ntpc.edu.tw/"},
{text: "新北市安坑國小",img:"anku.png",href: "https://www.takes.ntpc.edu.tw/"},
{text: "新北市信義國小",img:"thye.png",href: "https://www.thyes.ntpc.edu.tw/"},
{text: "新北市康橋國際學校秀岡校區",img:"kcis.png",href: "http://www.kcis.ntpc.edu.tw/_XiugangCampus/zh/index.html"},
{text: "雲林縣水碓國小",img:"sdps.png",href: "http://www.sdps.ylc.edu.tw/school/web/index.php"},
{text: "臺東縣東海國小",img:"dhip.png",href: "https://dhips.ttct.edu.tw/"},
{text: "香港漢鼎書院",img:"hana.png",href: "https://hanacademy.edu.hk/Zh-hant/AboutUs/StaffProfile/"},
{text: "國立中科實驗高中",img:"nehs.png",href: "https://www.nehs.tc.edu.tw/"},
{text: "台南市後壁國小",img:"hbes.png",href: "http://www.hbes.tn.edu.tw/"},
{text: "新北市福和國中",img:"fhjh.png",href: "https://www.fhjh.ntpc.edu.tw/"},
{text: "臺北市芳和國中",img:"fnjh.png",href: "http://www.fhjhs.tp.edu.tw/"},
{text: "臺北市景美女中",img:"cmgs.png",href: "https://www.cmgsh.tp.edu.tw/nss/p/index"},
{text: "香港弘立書院",img:"isf.png",href: "https://academy.isf.edu.hk/tc/"},
{text: "香港嗇色可立中學",img:"hola.png",href: "https://www.holap.edu.hk/"},
{text: "私立道明國際學校",img:"dish.png",href: "http://www.dishs.tp.edu.tw/"},
{text: "私立聖心女中",img:"shgs.png",href: "https://www.shgsh.ntpc.edu.tw/nss/p/index"},
{text: "香港耀中國際學校",img:"ycis.png",href: "https://www.ycis-hk.com/zh"},
{text: "義大國際學校",img:"iis.png",href: "https://www.iis.kh.edu.tw/tw/"},
]};




var data_biz = {webs: [
{text: "晨星出版",img:"mstar.png",href: "https://www.morningstar.com.tw/star/"},
{text: "木馬文化",img:"moma.png",href: "https://www.bookrep.com.tw/?md=gwindex&cl=press&at=presscontent&id=1"},
{text: "玉山社",img:"tipi.png",href: "http://www.tipi.com.tw/?fbclid=IwAR0Q1AH7-VxEcBTekquQB1n3mgSlrevk_3_3MQmqYfo0_d-6H-0Sd6ZwaT8"},
{text: "水滴文化",img:"gout.png",href: "https://www.facebook.com/gouttes.tw"},
{text: "培育文化",img:"peyu.png",href: "http://www.foreverbooks.com.tw/front/bin/ptlist.phtml?Category=69046"},
{text: "雅典文化",img:"yade.png",href: "http://www.foreverbooks.com.tw/front/bin/ptlist.phtml?Category=69065"},
{text: "讀品文化",img:"dupe.png",href: "http://www.foreverbooks.com.tw/front/bin/ptlist.phtml?Category=69056"},
{text: "大拓文化",img:"datu.png",href: "http://www.foreverbooks.com.tw/front/bin/ptlist.phtml?Category=69060"},
{text: "大是文化",img:"doma.png",href: "https://www.facebook.com/domainpub/"},
{text: "小鯨文創",img:"shar.png",href: "https://www.facebook.com/sharerocean/"},
{text: "堡壘文化",img:"info.png",href: "https://www.bookrep.com.tw/?md=gwindex&cl=press&at=presscontent&id=52"},
{text: "十字星球",img:"webn.png",href: "https://jslife.webnode.tw/"},
{text: "奧林文化",img:"olbook.png",href: "https://www.olbook.com.tw/"},
{text: "大穎文化",img:"dayi.png",href: "https://www.olbook.com.tw/"},
{text: "新雨出版",img:"newr.png",href: "https://www.facebook.com/newrain.publishing/?ref=page_internal"},
{text: "啟明出版",img:"chim.png",href: "https://www.chimingpublishing.com/news"},
{text: "親親文化",img:"kiss.png",href: "http://www.kissnature.com.tw/h/Index?key=788636607696"},
{text: "地平線文化",img:"horz.png",href: "https://www.andbooks.com.tw/index_publisher.php?publisher_url=41&mode=1"},
{text: "果力文化",img:"reve.png",href: "https://www.andbooks.com.tw/index_publisher.php?publisher_url=40&mode=1"},
{text: "漫遊者文化",img:"azoh.png",href: "https://www.andbooks.com.tw/index_publisher.php?publisher_url=33&mode=1"},
{text: "貓頭鷹出版",img:"owl.png",href: "https://www.cite.com.tw/publisher/about/13"},
{text: "亮語文創",img:"shin.png",href: "https://www.morningstar.com.tw/Press/Press.aspx?PBID=35"},
{text: "允晨文化",img:"yuch.png",href: "http://www.asianculture.com.tw/front/bin/home.phtml"},
{text: "大田出版",img:"data.png",href: "https://www.morningstar.com.tw/titan/"},
{text: "好讀出版",img:"good.png",href: "https://www.morningstar.com.tw/howdo/"},
{text: "愛智圖書",img:"aich.png",href: "http://www.aichi.com.tw/"},
{text: "小兵出版社",img:"bin.png",href: "https://www.facebook.com/bintonnet/"},
{text: "三之三文化",img:"33edu.png",href: "https://www.3-3edu.com.tw/book.htm"},
{text: "小魯文化",img:"tien.png",href: "https://www.tienwei.com.tw/"},
{text: "商周出版",img:"cite.png",href: "https://www.cite.com.tw/publisher/about/2"},
{text: "PanSci 泛科學",img:"pans.png",href: "https://pansci.asia/"},
{text: "尖端出版",img:"sharp.png",href: "https://www.spp.com.tw/productlist?item1=05"},
{text: "凌網電子書",img:"hyre.png",href: "https://ebook.hyread.com.tw/"},
{text: "三民書局",img:"thre.png",href: "https://www.sanmin.com.tw/"},
{text: "聯經出版",img:"link.png",href: "https://www.linkingbooks.com.tw/index.aspx"},
{text: "親子天下",img:"fami.png",href: "https://www.parenting.com.tw/"},
]};


var data_gov = {webs: [
{text: "新北市立圖書館",img:"ntpl.png",href: "https://www.library.ntpc.gov.tw/"},
{text: "臺北市立圖書館",img:"tpml.png",href: "https://tpml.gov.taipei/"},
{text: "臺東縣政府教育處",img:"ttedu.png",href: "http://www.boe.ttct.edu.tw/indexw.php"},
{text: "臺南市政府教育局",img:"tnedu.png",href: "https://www.tn.edu.tw/"},
{text: "新北市政府教育局",img:"ntpedu.png",href: "https://www.ntpc.edu.tw/"},
]};



